version: '3'

services:
  postgres:
    image: postgres

    ports:
      - 5432:5432

    environment:
    - POSTGRES_DB=groupby
    - POSTGRES_USER=groupby
    - POSTGRES_PASSWORD=groupby

  postgres_test:
      image: postgres

      ports:
        - 5433:5432

      environment:
      - POSTGRES_DB=groupby_test
      - POSTGRES_USER=groupby_test
      - POSTGRES_PASSWORD=groupby_test