POST http://localhost:8080/users/register
Content-Type: application/json

{
    "email": "betrayer11@gmail.com",
    "password": "password"
}

###

POST http://localhost:8080/users/getToken
Content-Type: application/json

{
    "email": "betrayer11@gmail.com",
    "password": "password"
}

###

GET http://localhost:8080/users/profile
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJiZXRyYXllcjExQGdtYWlsLmNvbSIsInJvbGUiOlt7ImlkIjoxLCJhdXRob3JpdHkiOiJST0xFX1VTRVIifV19.z5Wfl8Y7JRW5gzbabJcX18slPw53bvU-lSKfulSO-LmAuCYZq2TOMRyZxca84DqfFKFGjQi3Paux-6ViCkj_Kw

###