POST {{host}}/users/register
Content-Type: application/json

{
    "email": "betrayer11+1@gmail.com",
    "password": "password"
}

###

POST {{host}}/users/getToken
Content-Type: application/json

{
    "email": "betrayer11@gmail.com",
    "password": "password"
}

###

GET {{host}}/users/profile
Authorization: Bearer {{jwt}}

###
